[versions]
junit = "4.13.2"
lucene = "8.11.3"
icu4j = { require = "[70,73.2[", prefer = "72.1" }
randomizedrunner = "2.7.2"

[libraries]
junit = {group = "junit", name = "junit", version.ref = "junit"}
lucene-core = {module = "org.apache.lucene:lucene-core", version.ref = "lucene"}
lucene-analyzers-common =  {module = "org.apache.lucene:lucene-analyzers-common", version.ref = "lucene"}
lucene-codecs = {module = "org.apache.lucene:lucene-codecs", version.ref = "lucene"}
lucene-test-framework = {module = "org.apache.lucene:lucene-test-framework", version.ref = "lucene"}
icu4j = {module = "com.ibm.icu:icu4j", version.ref = "icu4j"}
randomizedtesting = {module = "com.carrotsearch.randomizedtesting:randomizedtesting-runner", version.ref = "randomizedrunner"}

[plugins]
nexus-publish = {id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0"}
